apiVersion: v1
kind: Pod
metadata:
  name: kink
  namespace: default
spec:
  containers:
  - image: m.daocloud.io/docker.io/library/docker:28.1.1-dind
    imagePullPolicy: IfNotPresent
    name: dockerd
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/run
      name: docker-sock
  - image: m.daocloud.io/docker.io/library/docker:28.1.1-dind
    imagePullPolicy: IfNotPresent
    command: 
    - sh
    - -c
    - |
      wget https://go.dev/dl/go1.24.3.linux-amd64.tar.gz;
      rm -rf /usr/local/go && tar -C /usr/local -xzf go1.24.3.linux-amd64.tar.gz;
      go install sigs.k8s.io/kind@v0.27.0
      kind create cluster --name kind --image m.daocloud.io/docker.io/kindest/node:v1.31.4 --retain; 
    name: kind
    env:
    - name: GOPROXY
      value: https://goproxy.cn
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run
      name: docker-sock
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - emptyDir: {}
    name: docker-sock
